repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      # - id: trailing-whitespace
      #   exclude: ^(data/|notebooks/|.*.csv)
      # - id: mixed-line-ending
      # - id: check-yaml
      #   exclude: ^(.*README.md|data/|notebooks/|.*.csv|deployment/)
      # - id: check-added-large-files
      # - id: check-json
      # - id: check-merge-conflict
      # - id: detect-private-key

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       args: [ "--profile", "black", "--filter-files" ]

  # - repo: https://github.com/psf/black
  #   rev: 23.1.0
  #   hooks:
  #     - id: black
  #       additional_dependencies: [ 'click==8.1.3' ]
  #       args:
  #         - --extend-exclude=E203

  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.16.1
  #   hooks:
  #     - id: gitleaks

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.6
  #   hooks:
  #   - id: bandit
  #     exclude: ^tests/

  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #   -   id: detect-secrets

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       args:
  #         - --max-line-length=128

  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: pytest tests
  #       language: system
  #       pass_filenames: false
  #       always_run: true
