version: 1
disable_existing_loggers: False

formatters:
  simple_request:
    format: "{asctime} - {name}:{lineno} - {levelname}: {message}"
    style: '{'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple_request
    stream: ext://sys.stdout
    filters: [ ]

loggers:
  llm_validation:
    level: DEBUG
    handlers: [console]
    propagate: False

root:
  level: WARNING
  handlers: [ console ]
